include $(PROJECT)/build_scripts/rules.mk

TARGET = linkedlist.so
SRCS = node.cpp \
	   linkedlist.cpp


# this is at the end because it relies on variables present in this file
include $(PROJECT)/build_scripts/build.mk